rewriter:
  host:
    - matcher: ^m[a-z]*\.hollandandbarrett\.com
      replacement: www.hollandandbarrett.com
    - matcher: m[a-z]*\.([a-z0-9\-\.]*hollandandbarrett\.com)
      replacement: $1
  link:
    host: m(?<prefix>[a-z]*)\.[a-z0-9\-\.]*hollandandbarrett\.com
    matcher: (^|\/\/|\"|\')(?!m$prefix\.)(www\.)?([a-z0-9\-\.]*)hollandandbarrett\.com
    replacement: $1m$prefix.$3hollandandbarrett.com
  cookie_domain:
    matcher: \.?(www\.)?([a-z0-9\-\.]*(hollandandbarrett\.com))
    replacement: .$3
    missing_replacement: .hollandandbarrett.com
